<h1 style="text-align:center; font-size:40px; font-family: 'Lucida Console', 'Courier New', 'monospace'; color:#87CEEB ">Array Data Structure</h1>

## Introduction 
<hr>

An array is a basic data structure in programming, widely applied for various purposes. It's a collection of elements with the same data type, stored in a contiguous, fixed-size fashion. Elements are accessed efficiently using unique numeric indexing(starts from 0). Arrays are also used to implement advanced data structure like stack, queue.

Here are some key characteristics and properties of arrays:
1. Fixed Size: Arrays have a fixed size.
2. Homogeneous: Arrays contain only single data type values.
3. Contiguous Memory: Elements are stored in contiguous memory blocks.
4. Supports Indexing: Arrays support indexing-based element access, with indexing possibly being 0-based or 1-based.
5. Constant-Time Access: Elements can be accessed in constant time using indexing.
6. Multidimensional Arrays: Arrays can have different dimensions, such as 2D, 3D, 4D, and so on.
   
`In Python, an array is not a built-in data structure` like in other languages such as C, C++, and Java. However, we can implement an array data structure in Python using lists. In Python, lists behave like arrays. The main difference between lists and arrays is that arrays can only store single-type data values, whereas lists can store data values of multiple types.
There is another way to implement arrays in Python, which is through the use of Numpy's array function. Numpy is an open-source library for the Python language, designed for scientific computation. Using Numpy's array function, we can define an array data structure in Python. Numpy's arrays, on the other hand, only contain single-type values.

## Implementation using Python
<hr>

In [2]:
# array using list
my_array = [1, 2, 3, 4, 5]
print(f"Array is(using list): {my_array}")

Array is(using list): [1, 2, 3, 4, 5]


In [3]:
# data type of array
# prints 'list' because we created array using list and list is also a data type in python
print(f"type of array is: {type(my_array)}")

type of array is: <class 'list'>


In [13]:
# multidimensinol arrays using list:----- 2D array
# for defining multidimensional arrays we just insert arrays into array, as we did below
nd_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print(f"Multidimensional array(2D): {nd_array}")

Multidimensional array(2D): [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


#### Array using Numpy array()

In [14]:
# loading numpy modules
import numpy as np

In [15]:
# using numpy.array, we can define arrays
np_array = np.array([1, 2, 3, 4, 5])
print(f"Array using numpy: {np_array}")

Array using numpy: [1 2 3 4 5]


In [16]:
# data type of numpy array
# prints 'numpy.ndarray' because we created array using numpy
print(f"type of array is: {type(np_array)}")

type of array is: <class 'numpy.ndarray'>


In [17]:
# we can also get dimension of arrays(if array is numpy array) using numpy.ndim 
print(f"Dimension of array: {np_array.ndim}")

Dimension of array: 1


In [24]:
# 3D Array or MultiDimensional Array
np_3Darray = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]])
print(f"3D Array using numpy:\n{np_3Darray}")

3D Array using numpy:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [25]:
# dimension of 3D array
print(f"Dimension of 3D array: {np_3Darray.ndim}")

Dimension of 3D array: 3


## Operations in Arrays
1. Insertion:- Inserting an element into array
2. Deletion:- Deleting an element from array
3. Update:- Update an element value with new value
4. Search:- Search an element into array
5. Accesssing:- Access an element from array using indexes

<hr>

In [27]:
# array for performing operations
my_array = [1, 2, 3, 4, 5]

#### Insertion

In [29]:
# insertion at specified position 
print(f"Array before insertion(at index): {my_array}")
my_array.insert(3, 500)
print(f"Array after insertion(at index): {my_array}")

Array before insertion(at index): [1, 2, 3, 4, 5, 100]
Array after insertion(at index): [1, 2, 3, 500, 4, 5, 100]


In [28]:
# insertion at end of array
print(f"Array before insertion(at end): {my_array}")
my_array.append(100)
print(f"Array after insertion(at end): {my_array}")

Array before insertion(at end): [1, 2, 3, 4, 5]
Array after insertion(at end): [1, 2, 3, 4, 5, 100]


#### Deletion

In [31]:
# deletion from location
print(f"Array before deletion(from loc): {my_array}")
item = my_array.pop(2)
print("Deleted element from 2 index: ", item)
print(f"Array after deletion(from loc): {my_array}")

Array before deletion(from loc): [1, 2, 3, 500, 4, 5]
Deleted element from 2 index:  3
Array after insertion(at end): [1, 2, 500, 4, 5]


In [30]:
# Deletion from end of array
print(f"Array before deletion(at end): {my_array}")
item = my_array.pop()
print("Deleted element: ", item)
print(f"Array after deletion(at end): {my_array}")

Array before deletion(at end): [1, 2, 3, 500, 4, 5, 100]
Deleted element:  100
Array after deletion(at end): [1, 2, 3, 500, 4, 5]


#### Update

In [33]:
print(f"Array before update: {my_array}")
# updating element at index 2 with value 100 
my_array[2] = 100
print(f"Array after update: {my_array}")

Array before update: [1, 2, 500, 4, 5]
Array after update: [1, 2, 100, 4, 5]


#### Search

In [34]:
# searching an element in list using index()
element_to_find = 100
# index number 
index = my_array.index(element_to_find)
print("element found at: ", index)

element found at:  2


#### Accessing an element

In [35]:
print("first element of array: ", my_array[0])
print("last element of array: ", my_array[-1])

first element of array:  1
last element of array:  5


## Advantages and Disadvantages of Array
<hr>
Arrays have their upsides and downsides. Let's break it down:

**Advantages of Arrays:**
1. **Quick Access:** Arrays let you get to elements super fast. Finding an element using its index is speedy, no matter the array's size.
2. **Predictable Memory:** They allocate memory in one go, which makes memory management predictable and efficient.
3. **Easy Looping:** You can easily go through all elements with a loop, thanks to the predictable memory layout.
4. **Multidimensional:** Arrays can go beyond one dimension, handling complex stuff like grids or matrices.
5. **Low-Level Control:** In low-level languages like C, you can directly work with arrays at the memory level, giving you precise control.

**Disadvantages of Arrays:**
1. **Set Size:** Arrays have a fixed size. Once you set it, you can't change it. This can be a hassle if you deal with collections of varying sizes.
2. **Awkward Inserts and Deletions:** Adding or removing elements can be a pain, especially in big arrays. You might need to shift stuff around.
3. **Data Type Limits:** Everything in an array must be the same data type. That's not great for mixed collections.
4. **Memory Waste:** If you make a big array but use only a bit, you might waste memory since all of it's reserved.
5. **DIY Functions:** Arrays in low-level languages lack built-in functions for things like searching or sorting. You'll have to code those yourself.
6. **No Auto-Resizing:** Regular arrays don't resize on their own. You'll have to make a new one and copy stuff over when it gets too small.
7. **Sparse Data Trouble:** Arrays struggle with sparse data – they reserve memory for everything, even empty slots.

To sum up, arrays are great for quick and efficient data handling, but their size and data type restrictions can be limiting. The right choice depends on your specific app's needs.

<h1 style="text-align:center; font-size:100px; font-family: 'Brush Script MT', cursive; color:#87CEEB">Thankyou</h1>